DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS peaks;

CREATE TABLE user (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE peaks (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    peak_1 FLOAT NOT NULL,
    peak_2 FLOAT NOT NULL,
    peak_3 FLOAT NOT NULL,
    peak_4 FLOAT NOT NULL,
    peak_5 FLOAT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES user (id)
);